### ISSUE TITLE
Update EC number field

### ISSUE THREAD

**Issue by JonathanRob** [SysBioChalmers/Human-GEM#127]
### Description of the issue:
The `eccodes` field in the HumanGEM model contains "non-standard" EC number entries, e.g., `spontaneous` or `non-enzymatic`, or they contain TCDB (Transporter Classification Database) IDs. 

These entries should be removed so that only EC numbers remain. The other information/IDs could be moved into the `rxnNotes` field, for example.

**I hereby confirm that I have:**
- [X] Checked that a similar issue does not exist already

**Comment by cfrainay** [comment]
Besides transporters and spontaneous, in the SBML there are a lot of invalid EC number references due to colons prefixing the EC code. If there are several numbers for the same entry there is also an added blank space in the identifier.org URI. If removed the URIs seems to reference the right resource. It seems to be only for HMR reactions, but I can't tell for sure.

**Comment by JonathanRob** [comment]
Good catch, @cfrainay. It seems that the colons preceding some EC codes are left there by the SBML export function because it strips off the `EC` prefix, but not the trailing colon. So, when we update the EC codes, the colons should either be removed or the writing function should be updated to strip off the colon. I'll make a note of this.

**Comment by JonathanRob** [comment]
Fixed in [v1.3.2](https://github.com/SysBioChalmers/Human-GEM/pull/168).
