### ISSUE TITLE
"Others" reaction and metabolite

### ISSUE THREAD

**Issue by mihai-sysbio** [SysBioChalmers/Human-GEM#197]
### Description of the issue:
@e0 has spotted the [`reaction "others"`](https://metabolicatlas.org/explore/gem-browser/human1/reaction/others). This reaction seems to act like a transport reaction with superpowers. The [`metabolite "others"`](https://metabolicatlas.org/explore/gem-browser/human1/metabolite/m10000s) doesn't seem to be used by any other reaction, it is just transported out. This reaction has been mentioned before [here](https://github.com/SysBioChalmers/Human-GEM/issues/117#issuecomment-533610992).

#### Expected feature/value/output:
Maybe these reaction and metabolite can be removed, or otherwise updated the usual format for transport reactions.

#### Current feature/value/output:
These reaction and metabolite are present but seem out of place.

#### Reproducing these results:
```bash
Human-GEM/model ❯  grep -inr "others" *
Human-GEM.yml:66521:      - name: "others"
Human-GEM.yml:211291:      - id: "others"
Human-GEM.yml:291316:      - name: "Exchange of others"
```

**I hereby confirm that I have:**
- [ ] Tested my code on my own computer for running the model
- [ ] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by Hao-Chalmers** [comment]
This `others` is a pool reaction that was inherited from the **HMR2** model. It was probably designed for particular simulation purposes, but the source and utilisation information for this reaction is lacking. Since the pool metabolite `others` was not used by any other reactions, this pool reaction and the accompanied exchange reaction could be removed after further confirmation.

**Comment by JonathanRob** [comment]
The `others` metabolite and reaction were removed in #213.
