### ISSUE TITLE
Discontinued/replaced NCBI gene id

### ISSUE THREAD

**Issue by haowang-bioinfo** [SysBioChalmers/Human-GEM#250]
### Description of the issue:
* It is found that in the gene annotation file `genes.tsv` one associated Entrez gene id [**107986084**](https://www.ncbi.nlm.nih.gov/gene/?term=107986084) was discontinued by NCBI and replaced with **7375**. 

#### Expected feature/value/output:
* The discontinued/replaced NCBI ids can be updated to the latest ones
* Ideally this update could be automated by the `get_ensembl_ID_mapping.py` script mentioned in #157

**I hereby confirm that I have:**
- [X] Done this analysis in the `master` branch of the repository
- [X] Checked that a similar issue does not exist already

**Comment by JonathanRob** [comment]
I noticed that the updated `genes.tsv` file (on `devel` after merging #251) contains the following entry in the NCBI (`geneEntrezID`) column for this gene: `7375;107986084`. I'm assuming that with later Ensembl updates that the deprecated ID (107986084) will be removed, but at the moment it's partially fixed.

Since the updated workflow with `genes.tsv` does not allow for manual modification of this file (thereby offloading the maintenance responsibilities to Ensembl), I will close this issue under the assumption that it will soon be fixed on Ensembl.

**Comment by Hao-Chalmers** [comment]
@JonathanRob no this issue is not fixed, let's keep it open.

**Comment by JonathanRob** [comment]
@Hao-Chalmers my reason for closing this issue is because, with our current workflow, the responsibility of maintaining the proper gene ID associations is now placed on Ensembl. So in reality, the issue should be made with Ensembl, not Human-GEM, since we do not have the power to fix this. But you can keep the issue open if you want to make users aware of the temporary existence of an expired NCBI ID in our `genes.tsv` file.

**Comment by pecholleyc** [comment]
But I agree to close this issue. Moreover I think the order of the IDs in `genes.tsv` is not random, Ensembl always puts the more meaningful ID at the left most position.

**Comment by Hao-Chalmers** [comment]
> Ensembl always puts the more meaningful ID at the left most position.

@pecholley if you have any evidence supporting this?

**Comment by mihai-sysbio** [comment]
@haowang-bioinfo I remember briefly looking in the documentation for the answer (evidence), but couldn't find it. Since both @JonathanRob and @pecholleyc were happy to close the issue, I will go ahead and close it.
