### ISSUE TITLE
MAM00080p, name and formula are not consistent

### ISSUE THREAD

**Issue by ANiknejad** [SysBioChalmers/Human-GEM#306]
https://metabolicatlas.org/explore/Human-GEM/gem-browser/metabolite/MAM00080p

the correct xref should be

https://pubchem.ncbi.nlm.nih.gov/compound/2S_6R_10R_-Trimethyl-hendecanoyl-CoA

but the formula reports to

https://pubchem.ncbi.nlm.nih.gov/compound/53481419

I am not sure how doing corrections here: to consider the name as correct and then to change the formula and the xref?

**Comment by JonathanRob** [comment]
@ANiknejad thank you for your help here. In general, I would trust the names of the metabolites over the xrefs.

As for the chemical formula, this starts to get tricky due to differences in e.g., protonation state, and is not so straightforward to fix. Changing the chemical formula will require re-balancing the reaction, but not necessarily _just_ the reaction(s) in which this metabolite is involved. It may propagate to other reactions/metabolites, requiring adjustment of their metabolite and/or reaction formula. 

So while I agree that we should try to keep metabolite formulas consistent with their associated xref(s), I would not recommend changing them unless it is done while accounting for the surrounding network.

**Comment by mihai-sysbio** [comment]
Has this issue been resolved or should it be closed?

**Comment by ANiknejad** [comment]
We can close this issue, we conserve the xref as it, because currently none CHEBI id can be associated to (2S,6R,10R)-trimethyl-hendecanoyl-CoA

(excepted the non-reviewed (2stars) CHEBI:180894, submitted by MetaboLights, a bit vicious circle then)
