### ISSUE TITLE
importYaml is slow

### ISSUE THREAD

**Issue by johan-gson** [SysBioChalmers/Human-GEM#387]
### Description of the issue:
Since the Human-GEM.mat file is removed from the repo we are down to using importYaml, which takes several minutes, while load('Human-GEM.mat') takes 1 s. If this is the intended use, it would be beneficial to speed this up. The way the code is written now, it performs tons of small reads from the file, which is super slow. The code could probably be enhanced a lot by reading the file in one big chunk into memory and then parse it from memory.

#### Expected feature/value/output:
It would just be much faster - right now it is annoyingly slow.

**I hereby confirm that I have:**
- [ ] Tested my code on my own computer for running the model
- [ ] Done this analysis in the `main` branch of the repository
- [ ] Checked that a similar issue does not exist already

**Comment by johan-gson** [comment]
Aha, so the .mat file will still be available in the main branch. It is still a bit complicated, the code cannot really rely on that the file is there then, such as a tutorial, or can it?

**Comment by mihai-sysbio** [comment]
Perhaps you're looking for [this tutorial](https://sysbiochalmers.github.io/Human-GEM-guide/getting_started)?

**Comment by johan-gson** [comment]
Most useful, thanks! But it is still very slow :)

**Comment by johan-gson** [comment]
When I look closer at it, it may not be the file reading, but it could be tested easily. The file reading could easily be fixed using readlines(filename), and just loop over the lines instead of checking for eof. But I'm not sure it will help that much. It could also be for example the regexp.

**Comment by edkerk** [comment]
With `profile on; model=importYaml('../../model/Human-GEM.yml'); profile viewer` it becomes clear it is slow not because it is _read_ one line at a time, but because it is _processed_ one line at a time. More precisely, each field is growing by one entry each time.

line 289 is run 166181 times, taking 61 seconds in total:
```matlab
    model.(fieldName) = [model.(fieldName); {value}];
```

Refactoring of the code could greatly speed this up, if the function would instead: (1) read the whole file at once; (2) split the data in the part describing reactions and metabolites and process separately; (3) use regexp to find e.g. first line of each reaction; (4) use regexp to extract all entries for a certain field type (e.g. `eccodes`) all at once.

I can imagine that the tricky part will be to handle cases where e.g. not all reactions have an entry for a particular field. But with some clever coding, I'm sure this can be managed :).

But maybe you see some other opportunities?

**Comment by johan-gson** [comment]
just preallocating the vectors to something large, and fix that in the end, would likely speed this up a lot - that is a very quick fix :)

**Comment by mihai-sysbio** [comment]
> line 289 is run 166181 times, taking 61 seconds in total:

I'm not sure to what extent this is the problem, since the `yml` file has 311891 lines, so it's parsing a field in only 50% of the time.

**Comment by johan-gson** [comment]
Still 61 seconds to cut :)

**Comment by edkerk** [comment]
#393 addresses the issue of extending model fields.
The next slowest parts are `constructS` (14-23% of time) from RAVEN, which can maybe be improved a bit, and otherwise `tokenizeYamlLine` (~10% of time), where I do not see much opportunity for improvement.

**Comment by edkerk** [comment]
Combined with `constructS` from this PR https://github.com/SysBioChalmers/RAVEN/pull/424, it now takes <40 sec to load the model on my PC.

`tokenizeYamlLine` is now responsible for ~35% of the duration, could maybe be reduced by first reading the whole file, run `tokenizeYamlLine` on all lines, and then loop through vectors of `line_key` and `line_value` to fill the model fields, where the loop largely follws the current structure.

**Comment by johan-gson** [comment]
Nice work! Maybe we can close this then?

**Comment by mihai-sysbio** [comment]
I also find that https://github.com/SysBioChalmers/Human-GEM/pull/393 fully resolves this issue.
