### ISSUE TITLE
One or more equations contain metabolites that are not in model.metNames.

### ISSUE THREAD

**Issue by liuhl22** [SysBioChalmers/Human-GEM#566]
Dear Sir Or Madam

### Description of the issue:

I downloaded the TPM type tissue RNA-sqe database from GTEx. However, following the code in "GEM extraction using ftINIT", when running the "model2" stage, the speed is slow. Just running the "model2" stage takes 1-2 hours and an error occurs. 

**Description of error:**

Error using dispEM
One or more equations contain metabolites that are not in model.metNames. Set allowNewMets to true to
allow this function to add metabolites or use addMets to add them before calling this function

Error in addRxns (line 620)
            dispEM(EM);

Error in ftINITFillGapsForAllTasks (line 293)
            tModel=addRxns(tModel,rxn,3);

Error in ftINIT (line 364)
        [outModel,addedRxnMat] = ftINITFillGapsForAllTasks(initModelNoExc,refModelNoExc[],true,min(rxnScores2nd,-0.1),prepData.taskStruct,paramsFT,verbose);

Error in ftINIT_model1 (line 13 )
model2 = ftINIT(prepData, data_struct.tissues{1}, [], [], data_struct, {}, getHumanGEMINITSteps('1+1'), false, true);
 

 **attempt:**

I then followed the "GEM extraction using ftINIT" step using TPM's RNA-sqe data from Zenodo. The "model2" step had no error and produced a rapid result.

I am using matlab 2022b and Gurobi 10.0.1, and Human-GEM and RAVEN are updated to the latest version.

Any help would be appreciated. Thank you very much.

**I hereby confirm that I have:**

 

- [ ] Tested my code on my own computer for running the model

 

- [ ] Done this analysis in the main branch of the repository

**Comment by mihai-sysbio** [comment]
Hi @liuhl22! Thanks for reaching out about this bug.

As mentioned [here in the guide](https://sysbiochalmers.github.io/Human-GEM-guide/gem_extraction/#load-and-prepare-the-reference-model-for-use-with-ftinit):
> For version 1.12.0 of Human-GEM, the prepData is available in the Zenodo .zip file.

With the latest release of Human-GEM [`1.15`](https://github.com/SysBioChalmers/Human-GEM/releases/tag/v1.15.0), some metabolites have been changed from 1.12, e.g., see the last lines in [the file of deprecated metabolites](https://github.com/SysBioChalmers/Human-GEM/blame/main/data/deprecatedIdentifiers/deprecatedMetabolites.tsv). Using the Zenodo-provided `prepData` based on Human-GEM 1.12 with 1.15 later on would trigger an error such as the encountered 
```
One or more equations contain metabolites that are not in model.metNames
```

Therefore, a clarifying question - which `prepData` are you using?

**Comment by liuhl22** [comment]
@mihai-sysbio, thanks for your reply.

The prepData I am using is generated by **human 1.14** and uses the following code:
`prepData = prepHumanModelForftINIT(ihuman, false, 'path/to/HumanGEM/data/metabolicTasks/metabolicTasks_Essential.txt', 'path/to/HumanGEM/model/reactions.tsv');`

Is not the prepData in the Zenodo. zip file.

Strangely, although the model I am using now is Human 1.15 and prepData is generated by human 1.14, there is no error reported in the process of model 1 generation, but the model 1 generation speed is very slow and there are errors in model 2.

I will try to generate new prepData from Human 1.15 and then apply it to model 1 and model 2 generation.

**Comment by feiranl** [comment]
@johan-gson Johan, could you help fix this issue?

**Comment by liuhl22** [comment]
Hi John, thanks for your reply. The size of my RNA-sqe file is over 45MB, so I chose a portion of the sample to upload
[gene_tpm_kidney_cortex2.txt](https://github.com/SysBioChalmers/Human-GEM/files/11721767/gene_tpm_kidney_cortex2.txt)
When I use this database to generate model by ftINIT, the speed are still slow。
Interestingly，when I integrated these kidney RNA-sqe data behind the TPM data ([gtexSampForTutorialTPM.txt](https://github.com/SysBioChalmers/Human-GEM/files/11722191/gtexSampForTutorialTPM.txt))in the case file, the speed of generation was greatly improved, but the generating model file is abnormally large, about 7G.
If the kidney RNA-sqe data was placed in front of the data in the case file, the speed of generationwas still slow.

**Comment by johan-gson** [comment]
@liuhl22 Hi, I have tested the first sample in the kidney cortex, it worked fine for me and finished in maybe 30 seconds. The code below. A very important step is to remove the versions from the genes, otherwise everything will go south, I suspect that is what happened to you.

Another thing to watch out for right now is that the essential tasks file in the latest version of Human-GEM is incorrect, I recommend copying it from devel. A metabolite changed name from GAP to something long, and was not updated in the tasks file. Let me know if you can get this to work!

%Runs prepInitModel for Human-GEM, including filtering of reactions.
cd 'C:/Temp'

%load Human-GEM and tasks
%load('C:/Work/MatlabCode/components/human-GEM/Human-GEM_1_12/Human-GEM/model/Human-GEM.mat')
load('C:/Code/components/Human-GEM/Human-GEM/model/Human-GEM.mat')

m = ihuman;
m.grRules = simplifyGrRules(m.grRules, true);

prepDataHumanGEM = prepHumanModelForftINIT(m, false, ...
                    'C:/Code/Components/Human-GEM/Human-GEM/data/metabolicTasks/metabolicTasks_Essential.txt', ...
                    'C:/Code/Components/Human-GEM/Human-GEM/model/reactions.tsv');
save('prepDataHumanGEM.mat','prepDataHumanGEM');

tbl = readtable('gene_tpm_kidney_cortex2.txt');

arrayData = struct(); 
arrayData.genes = extractBefore(tbl.Name,strlength('ENSG00000240361')+1); %remove version
arrayData.levels = tbl.GTEX_11GS4_2326_SM_5A5KS; %This could be a matrix with several columns, I was just lazy here
sum(arrayData.levels) %ok, 10^6
arrayData.tissues = {'1'}; %or the column names from gtex
arrayData.threshold = 1;
mres = ftINIT(prepDataHumanGEM,arrayData.tissues{1},[],[],arrayData,{},getHumanGEMINITSteps('1+0'),false,true,[]);

**Comment by feiranl** [comment]
After testing it myself, it is successful. Thus, I close this issue. Please feel free to reopen this issue if there is further issues.
