### ISSUE TITLE
Proposed fixes to DHAP <=> sn-glycerol-3-phosphate reactions

### ISSUE THREAD

**Issue by jreimertz** [SysBioChalmers/Human-GEM#599]
I recently came across five reactions that are involved in the conversion of DHAP to sn-glycerol-3-phosphate in glycolysis that I've included below:

| Reaction ID | Reaction String                                                                                                  | GPR               |
| ------------- | ----------------------------------------------------------------------------------- | -------------- | 
| MAR01169  | FAD [m] + sn-glycerol-3-phosphate [c] ⇒ DHAP [c] + FADH2 [m]                   | GPD2             |
| MAR00483  | sn-glycerol-3-phosphate [c] + ubiquinone [m] ⇒ DHAP [c] + ubiquinol [m]   | GPD2             |
| MAR00482  | FAD [c] + sn-glycerol-3-phosphate [c] ⇒ DHAP [c] + FADH2 [c]                      | GPD2             |
| MAR00479  | DHAP [c] + H+ [c] + NADH [c] ⇒ NAD+ [c] + sn-glycerol-3-phosphate [c]     | GPD1L, GPD1 |
| MAR00478  | DHAP [c] + H+ [c] + NADPH [c] ⇒ NADP+ [c] + sn-glycerol-3-phosphate [c] | GPD1             |

The Uniprot page for [GPD2](https://www.uniprot.org/uniprotkb/P43304/entry) supports the reaction MAR00483, but contradicts MAR00482 and MAR01169. Similarly, the Uniprot pages for [GPD1](https://www.uniprot.org/uniprotkb/P21695/entry) and [GPD1L ](https://www.uniprot.org/uniprotkb/Q8N335/entry) support MAR00479 but don't include MAR00478. Additionally, I wasn't able to find any papers that mentioned NADPH/NADP+ in this reaction in humans.

As a result, I think it would be appropriate to remove reactions MAR00482, MAR00478, and MAR01169

**Comment by feiranl** [comment]
Good catch! 
I am ok with removing MAR00478 and MAR00482.
I am not sure about this. I am not familiar with this protein, just from Uniprot annotation, it appears to have FAD binding region. 

> Cofactor
> Protein has 1 cofactor binding site:
> FAD ([UniProtKB](https://www.uniprot.org/uniprotkb?query=cc_cofactor_chebi:%22CHEBI:57692%22) | [Rhea](https://www.rhea-db.org/rhea?query=CHEBI:57692)| [CHEBI:57692](https://www.ebi.ac.uk/chebi/searchId.do?chebiId=CHEBI:57692) ) 

@haowang-bioinfo what is your idea about this?

**Comment by haowang-bioinfo** [comment]
@jreimertz thanks for the checking

> I am ok with removing MAR00478 and MAR00482. Removing MAR00482 since the protein is a mitochondria protein.

agree

**Comment by JonathanRob** [comment]
The FAD-containing reaction (MAR01169) could be seen as part of a 2-step reaction with:

[MAR06911](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06911): FADH2 [m] + ubiquinone [m] ⇔ FAD [m] + ubiquinol [m]

whereby the FAD cofactor acts as an intermediate electron carrier.

MAR00482, the FAD reaction taking place in the cytosol, is a bit weirder because there is no equivalent to MAR06911 in the cytosol, so it would instead be a 3-step reaction including MAR06911 above and:

[MAR06513](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06513): FAD [m] + FADH2 [c] ⇔ FAD [c] + FADH2 [m]

So I agree with @feiranl to remove MAR00482 since it takes place in the cytosol and would have a strange mechanism, but I would not necessarily remove MAR01169.

**Comment by haowang-bioinfo** [comment]
> MAR00482, the FAD reaction taking place in the cytosol, is a bit weirder because there is no equivalent to MAR06911 in the cytosol, so it would instead be a 3-step reaction including MAR06911 above and:
[MAR06513](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06513): FAD [m] + FADH2 [c] ⇔ FAD [c] + FADH2 [m]
So I agree with @feiranl to remove MAR00482 since it takes place in the cytosol and would have a strange mechanism, but I would not necessarily remove MAR01169.

yes, MAR00482 should be removed for sure, as well as MAR00478 (use NADPH)

> The FAD-containing reaction (MAR01169) could be seen as part of a 2-step reaction with:
[MAR06911](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06911): FADH2 [m] + ubiquinone [m] ⇔ FAD [m] + ubiquinol [m]
whereby the FAD cofactor acts as an intermediate electron carrier.

this MAR06911 is very much relevant, and probably better pair with `MAR00449: FAD [m] + sn-glycerol-3-phosphate [m] ⇒ DHAP [m] + FADH2 [m]` than `MAR01169: FAD [m] + sn-glycerol-3-phosphate [c] ⇒ DHAP [c] + FADH2 [m]`. And both MAR00449 and MAR01169 have GPR GPD2, and the latter should be removed.

**Comment by Devlin-Moyer** [comment]
So a question about compartments: does the [m] compartment include both the intermembrane space and the mitochondrial matrix? Because the reactions catalyzed by GPD1 and GPD2 both specifically involve DHAP and glycerol-3-phosphate in the intermembrane space, not the mitochondrial matrix. And I've come across a lot of papers like [this](https://www.sciencedirect.com/science/article/pii/S0005272812010894) that characterize the metabolite pools of the cytosol and intermembrane space to be largely equivalent and both clearly distinct from the metabolic composition of the mitochondrial matrix:
>The OMM often is considered a relatively non-specific ‘sieve’ that is permeable for most molecules up to 5 kDa. However, recent findings indicate a higher degree of selectivity and regulation and potentially also the existence of additional OMM transporters (Kruger et al., [2017](https://bpspubs.onlinelibrary.wiley.com/doi/full/10.1111/bph.14480#bph14480-bib-0080)). In comparison, the IMM is impermeable and metabolites require dedicated transporters – many of which are coupled to the anti/symport of other metabolites or to the mitochondrial membrane potential. As there are not IMM transporters for all metabolites, some metabolites have to be converted to other metabolites for which transporters exist. For example, the malate–aspartate shuttle serves to export oxaloacetate from the matrix to the cytosol or to transfer NADH from the cytosol to the matrix. As there is no IMM transporter for oxaloacetate, it has to be converted to aspartate, which can be transported out of the matrix in an antiport with glutamate. In the cytosol/IMS [the aspartate aminotransferase GOT2 is found in the IMS proteome (Hung et al., [2014](https://bpspubs.onlinelibrary.wiley.com/doi/full/10.1111/bph.14480#bph14480-bib-0071))], aspartate is converted back to oxaloacetate, which is reduced by NADH, yielding malate, which is transported into the matrix in an antiport with 2-oxoglutarate.
Also it sort of seems like the [i] compartment is intended to represent the intermembrane space? Even though it's nominally named "inner_mitochondria", the electron transport chain reactions (MAR06914, MAR06918, MAR06921) move H<sup>+</sup> from [m] to [i], and ATP synthase (MAR06916) returns them from [i] back to [m].
All that is to say: should the reaction that GPD2 catalyzes involve DHAP [i] and sn-glycerol-phosphate [i] instead of the [c] or [m] versions of those metabolites? If we think [c] includes the intermembrane space, then we should keep MAR00483 and remove MAR00449, but if we think [m] includes the intermembrane space (which I think is inaccurate), then we should keep MAR00483 and remove MAR00449.

**Comment by Devlin-Moyer** [comment]
> The FAD-containing reaction (MAR01169) could be seen as part of a 2-step reaction with:
> 
> [MAR06911](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR06911): FADH2 [m] + ubiquinone [m] ⇔ FAD [m] + ubiquinol [m]
> 
> whereby the FAD cofactor acts as an intermediate electron carrier.
 
If we're keeping MAR01169 because GPD2 uses electrons from DHAP to reduce (tightly-bound) FAD, which it then also uses to reduce ubiquinone, then we should probably add it to the GPR of MAR06911, which currently contains the subunits of the electron transfer flavoprotein heterodimer (ETFA and ETFB) and [ETFDH](https://www.uniprot.org/uniprotkb/Q16134/entry), which oxidizes the FAD bound to ETFA/B and reduces ubiquinone, and one of the subunits of the succinate dehydrogenase complex (SDHC). Since those enzymes are all part of distinct complexes, it seems like there's precedent for adding in another clearly distinct enzyme that catalyzes this reaction.

**Comment by Devlin-Moyer** [comment]
Here's a list of all similar pairs of reactions I could find (I'm reasonably confident this is all of them) with one FAD-dependent version and one ubiquinone-dependent version:
* MAR02035 (ubiquinone) and MAR03121 (FAD)
* MAR03211 (ubiquinone) and MAR03212 (FAD)
* MAR03751 (ubiquinone) and MAR03752 (FAD)
* MAR03783 (ubiquinone) and MAR03784 (FAD)
* MAR04242 (ubiquinone) and MAR04243 (FAD)
* MAR03769 (ubiquinone) and MAR03770 (FAD)
* MAR03838 (ubiquinone) and MAR08611 (FAD)
* MAR04652 (ubiquinone) and MAR08743 (FAD)
* MAR02366 (ubiquinone) and MAR03163 (FAD)
* MAR02367 (ubiquinone) and MAR03135 (FAD)
* MAR02639 (ubiquinone) and MAR03149 (FAD)
* MAR02370 (ubiquinone) and MAR03128 (FAD)
* MAR02372 (ubiquinone) and MAR03156 (FAD)
* MAR02373 (ubiquinone) and MAR03142 (FAD)

Also it feels relevant to note that several of the ubiquinone-dependent reactions in this list have inaccurate GPRs; they have ACOX1 and ACOX3 in them, which are peroxisomal proteins according to Uniprot and also several papers I found; their FAD-dependent duplicates have the correct GPRs

According to [this paper](https://www.sciencedirect.com/science/article/pii/S0378111921000019?casa_token=SLjPfCpnKcIAAAAA:YdfmRewhuBvHOvxh2I_lvHqHRTvk-1nc6kgJGE8tTCWE952vo7l_7R7SA0ArDuISzsaXZS5dbgM) the following enzymes interact with ETFA/B:
* ACADVL
* ACADL
* ACADM
* ACADS
* ACADSB
* ACAD9
* ACAD10
* ACAD11
* GCDH
* IBDH
* IVD
* SARDH
* DMGDH
* D2HGDH
Most of these are in Human-GEM and are collectively associated with hundreds of reactions, nearly all of which use FAD and not ubiquinone (the exceptions are above), so whatever we decide here should apply to all of these reactions as well.

There's also MAR00562, which turns FADH2 and Electron Flavoprotein Oxidized into FAD and Electron Flavoprotein Reduced, and MAR00563, which turns Electron Flavoprotein Reduced and ubiquinone into Electron Flavoprotein Oxidized and ubiquinol, which seem redundant with MAR06911 (I think MAR00562 and MAR00563 should be dropped cuz ETFA and ETFB and ETFDH are all already in the GPR of MAR06911), but hypothetically another option here would be to have all of the reactions associated with proteins that are known to interact with ETFA/B as the intermediate between FAD and ubiquinone reduced Electron Flavoprotein Oxdized instead of FAD.

There's also MAR04575: (S)-dihydroorotate + ubiquinol <-> orotate + ubiquinone, catalyzed by DHODH. DHODH is also a flavoenzyme but is one of the few human flavoenzymes that uses FMN instead of FAD as its intermediate electron acceptor. DHODH is capable of reducing ubiquinone, so we could keep it as-is, but if we want it to be consistent with all these other reactions, we would have to create a mitochondrial FMN metabolite (currently only exists in cytosol and extracellular compartments) and a new reduced FMN metabolite (which doesn't exist), and a new reaction catalyzed by DHODH that reduces ubiquinone with reduced FMN.

**Comment by haowang-bioinfo** [comment]
> So a question about compartments: does the [m] compartment include both the intermembrane space and the mitochondrial matrix? Because the reactions catalyzed by GPD1 and GPD2 both specifically involve DHAP and glycerol-3-phosphate in the intermembrane space, not the mitochondrial matrix.

yes, GPD2 is localized in the intermembrane space, instead of the mitochondrial matrix

> Also it sort of seems like the [i] compartment is intended to represent the intermembrane space? Even though it's nominally named "inner_mitochondria", the electron transport chain reactions (MAR06914, MAR06918, MAR06921) move H+ from [m] to [i], and ATP synthase (MAR06916) returns them from [i] back to [m]. Also there are apparently a ton of reactions that do cotransport of a cytosolic metabolite into or out of the mitochondria accompanied by H+ [i], so, despite the name, it seems like [i] is functionally a representation of the intermembrane space, but that [c] is also sort of treated as equivalent to/containing the intermembrane space?

yes, the [i] compartment is meant to represent the intermembrane space

**Comment by haowang-bioinfo** [comment]
> Here's a list of all similar pairs of reactions I could find (I'm reasonably confident this is all of them) with one FAD-dependent version and one ubiquinone-dependent version:

Very good - might be better move this to a separate issue?

**Comment by haowang-bioinfo** [comment]
> If we're keeping MAR01169 because GPD2 uses electrons from DHAP to reduce (tightly-bound) FAD, which it then also uses to reduce ubiquinone, then we should probably add it to the GPR of MAR06911, which currently contains the subunits of the electron transfer flavoprotein heterodimer (ETFA and ETFB) and [ETFDH](https://www.uniprot.org/uniprotkb/Q16134/entry), which oxidizes the FADH2 bound to ETFA/B and reduces ubiquinone, and one of the subunits of the succinate dehydrogenase complex (SDHC). Since those enzymes are all part of distinct complexes, it seems like there's precedent for adding in another clearly distinct enzyme that catalyzes this reaction.

if provided with supporting evidence, GPD2 can be added to the GPR of MAR01169 (or MAR00449)

**Comment by JonathanRob** [comment]
Regarding the [i] compartment:

As @haowang-bioinfo mentioned above, it represents the mitochondrial intermembrane space. While it is true that there are many more enzymes/reactions/metabolites that should actually be in the [i] compartment rather than [m], this is generally not done to avoid an unnecessarily large model.

The [i] compartment was primarily implemented as a tool to allow the simulation of energy exchange related to membrane concentration gradients (e.g., proton motive force), rather than to represent the actual contents of the intermembrane space in reality (described in detail in the supporting text of the [Human1](https://doi.org/10.1126%2Fscisignal.aaz1482) publication). The [i] compartment is used to tightly control the transport of protons and other metabolites whose movement across the membrane is coupled to some energy-consuming or producing reaction; e.g., ATP synthase. Without the isolation of the [i] compartment, it becomes very difficult to prevent energy leakage because there are so many reactions that can produce/consume protons in a way that allow the model to "cheat" and create energy using combinations of such reactions. 

So in general, the [m] compartment is used to hold all the reactions, metabolites, and enzymes that are present in the mitochondrial matrix or the intermembrane space, _except_ for those that use or affect the membrane gradient in some way. Otherwise, the model would become much larger since many metabolites/reactions would need to be duplicated in the [i] compartment, and would make it more difficult to debug energy leakage issues related to that compartment.

**Comment by feiranl** [comment]
A little bit summary of above discussions to make sure that I understand correctly.

1. we are all good about removing MAR00478 and MAR00482 
2. keep reactions in [m]; since [i] is isolated for energy gradient
3. still wait for discussions for ubiquinone and FAD in #607 , then we can decide to remove `MAR00483` or `MAR01169`

**Comment by Devlin-Moyer** [comment]
In #607 and #613, we decided to remove `MAR00483`, since `GDP2` uses an FAD cofactor as an intermediate electron carrier between sn-glycerol-3-phosphate and ubiquinone, and `MAR06911` already represents the reduction of ubiquinone with FADH<sub>2</sub>, which resolved the only remaining open question about the proposed changes in this issue, so all that's left is:
- Remove `MAR00478` because there's no evidence that `GPD1` or `GPD1L` can use NADP(H) in addition to NAD(H)
- Remove `MAR00482` because `GPD2` is definitely localized to the inner mitochondrial membrane, so it should use FAD(H<sub>2</sub>) [m] and not [c]
are we good to go with opening a PR to make those changes?

**Comment by haowang-bioinfo** [comment]
fixed in #710, feel free to reopen
