### ISSUE TITLE
Suggested Removal of MAR03940

### ISSUE THREAD

**Issue by jreimertz** [SysBioChalmers/Human-GEM#632]
MAR03940 is a duplicate of MAR08539 and MAR08538, and has a slightly wrong GPR since [PAH](https://www.uniprot.org/uniprotkb/P00439/entry) only catalyzes the first step in this reaction represented by MAR08539, the second step represented by MAR08538 is catalyzed by [PCBD1](https://www.uniprot.org/uniprotkb/P61457/entry) or [PCBD2](https://www.uniprot.org/uniprotkb/Q9H0N5/entry)). 

If we wanted to keep the one-step reaction the GPR would need to be updated to include PCBD1 and PCBD2

**Comment by haowang-bioinfo** [comment]
thanks for reporting this. Yes, two-step version is more preferred than one-step in general.

Both [PCBD1](https://www.uniprot.org/uniprotkb/P61457/entry) and [PCBD2](https://www.uniprot.org/uniprotkb/Q9H0N5/entry) are localized in nucleus, while PCBD1 also resides in cytosol. Should a cytosol version of MAR08538 be added? @jreimertz

**Comment by jreimertz** [comment]
Isn't [MAR08538](https://metabolicatlas.org/explore/Human-GEM/gem-browser/reaction/MAR08538) already cytosolic?

**Comment by haowang-bioinfo** [comment]
sorry! what I mean is to add counterparts of MAR08538 and MAR08539 in nucleus.

**Comment by jreimertz** [comment]
Ah, yes I agree that would make sense! 

Would it also make sense to add HNF1B to the GPR of MAR08538? According to the [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3935582/) cited by Uniprot, HNF1B interaction with PCBD1 determines its subcellular localization.

**Comment by haowang-bioinfo** [comment]
> Would it also make sense to add HNF1B to the GPR of MAR08538? According to the [paper](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3935582/) cited by Uniprot, HNF1B interaction with PCBD1 determines its subcellular localization.

yes, this paper reported interaction of PCBD1 with HNF1B in determining subcellular localization and enhancing promoter activation of HNF1B. However, there is no evidence associating HNF1B with dihydropteridine reductase activity. In addition, the nuclear-version may not be needed, because it seems only cytosolic PCBD1 has enzymatic activity based on following discussion:

`PCBD1 monomers are small molecules that can passively diffuse from the cytosol into the nucleus.[36] It was suggested that, by assembling through the same interface, PCBD1 homotetramer and PCBD1–HNF1 complexes are mutually exclusive.[17] In our immunocytochemical analysis, the HNF[1] B mutants p.Gln25[3] Pro and p.His324Ser325fsdelCA significantly stimulated a cytosolic localization of PCBD1 compared with the nuclear PCBD1 localization observed in the presence of wild-type HNF1B. This finding suggests that HNF1B mutations may disturb the stability of the PCBD1–HNF1 complexes in the nucleus and therefore, favor the formation of PCBD1 homotetramers in the cytosol of the cell. The reduced nuclear localization of PCBD1 will indirectly result in a decreased coactivation of HNF1B and could contribute to the hypomagnesemia observed in some HNF1B patients.`
```

**Comment by haowang-bioinfo** [comment]
fixed in #702
